# Generated by Django 3.1.1 on 2020-09-12 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyview',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 9, 3, 17, 89902, tzinfo=utc)),
        ),
    ]
